version: '3.8'

services:
  db:
    image: mariadb:11
    container_name: shopping-cart-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopping_cart_localization
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/java/org/example/java_shopping_cart/db/setup:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - "8082:8080"

  app:
    build: .
    container_name: shopping-cart-app
    depends_on:
      db:
          condition: service_healthy
    environment:
      DB_PASS: root
      DB_URL: jdbc:mariadb://db:3306/shopping_cart_localization
      DB_USER: root
      DISPLAY: host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
volumes:
  db_data: