sonar.projectKey= javafx_shopping_cart
sonar.projectName=java_shopping_cart
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.exclusions=**/controllers/**,**/ShoppingCartApplication.java,**/Launcher.java
sonar.host.url=http://localhost:9000
sonar.token= sqa_1006a313d44c501858add8da4b0cb8e9e893bcf1